name: Check
on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: sdrush
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run formatting check
        run: nix develop --command just format
        if: matrix.os == 'ubuntu-latest'

      - name: Lint GitHub Actions
        run: nix develop --command just lint-actions
        if: matrix.os == 'ubuntu-latest'

      - name: Run linting
        run: nix develop --command just lint

      - name: Run flake checks
        run: nix develop --command just check

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: sdrush
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Security Audit
        run: nix develop --command just security-scan
