name: Check
on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            trusted-users = root runner
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: sdrush
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run formatting check
        run: nix shell nixpkgs#just nixpkgs#treefmt -c just format
        if: matrix.os == 'ubuntu-latest'

      - name: Lint GitHub Actions
        run: nix shell nixpkgs#actionlint -c actionlint
        if: matrix.os == 'ubuntu-latest' # Only need to lint once

      - name: Run linting
        run: nix shell nixpkgs#just nixpkgs#statix nixpkgs#deadnix -c just lint

      - name: Run flake checks
        run: nix shell nixpkgs#just -c just check

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            trusted-users = root runner
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: sdrush
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Security Audit
        run: nix shell nixpkgs#just -c just security-scan
